ga:
    selection_percentage: 0.35
    mutation_prob:
        - 0.02
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
    crossover_prob:
        - 0.3
        - 0.45
        - 0.65
        - 0.8
    population:
        - 40
        - 50
        - 60

extra:
    iterations: 100
    region: blr
    lats_range:
        - 12.8627000
        - 13.1002000
    lons_range:
        - 77.4358000
        - 77.7846000
    radius: 4
    n_circles:
        - 12
    mutation_range:
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
