ga:
    selection_percentage: 0.35
    mutation_prob:
        - 0.01
    crossover_prob:
        - 0.65
    population:
        - 40

extra:
    iterations: 1000
    region: blr
    lats_range:
        - 12.8627000
        - 13.1002000
    lons_range:
        - 77.4358000
        - 77.7846000
    radius: 4
    n_circles:
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
    mutation_range:
        - 0.02
