ga:
    selection_percentage: 0.35
    mutation_prob:
        - 0.01
        - 0.02
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
        - 0.09
    crossover_prob:
        - 0.65
    population:
        - 40

extra:
    iterations: 1000
    region: dlh
    lats_range:
        - 28.5504000
        - 28.7330000
    lons_range:
        - 77.0423000
        - 77.3911000
    radius: 4
    n_circles:
        - 9
    mutation_range:
        - 0.02
