ga:
    selection_percentage: 0.35
    mutation_prob:
        - 0.01
    crossover_prob:
        - 0.6
    population:
        - 40

extra:
    iterations: 1000
    region: dlh
    lats_range:
        - 28.5504000
        - 28.7330000
    lons_range:
        - 77.0423000
        - 77.3911000
    radius: 4
    n_circles:
        - 8
        - 9
        - 10
        - 11
        - 12
    mutation_range:
        - 0.04
