ga:
    selection_percentage: 0.35
    mutation_prob:
        - 0.01
        - 0.02
        - 0.035
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
        - 0.09
        - 0.10
    crossover_prob:
        - 0.2
        - 0.3
        - 0.4
        - 0.45
        - 0.65
        - 0.7
        - 0.8
    population:
        - 30
        - 40
        - 50
        - 60

extra:
    iterations: 150
    region: dlh
    lats_range:
        - 28.5504000
        - 28.7330000
    lons_range:
        - 77.0423000
        - 77.3911000
    radius: 4
    n_circles:
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
    mutation_range:
        - 0.01
        - 0.02
        - 0.03
        - 0.04
        - 0.05
        - 0.06
        - 0.07
        - 0.08
