ga:
    selection_percentage: 0.35
    mutation_prob:
        - 0.06
    crossover_prob:
        - 0.65
    population:
        - 60

extra:
    iterations: 200
    region: blr
    lats_range:
        - 12.8627000
        - 13.1002000
    lons_range:
        - 77.4358000
        - 77.7846000
    radius: 4
    n_circles:
        - 12
    mutation_range:
        - 0.03
